import type { Projects } from "$utils/types";

// Curated from /code audit — 75 package.json scanned, grouped for portfolio mapping
// Add new projects by appending entries; keep `featured` to 3-5 hero items
// `path` is repo-relative for local reference; `links.demo/github` for UI

export const projects = [
  // ── Featured / Hero ──
  {
    id: "fair-share",
    slug: "fairshares",
    title: "FairShares",
    description:
      "AI-powered bill-splitting — scan a receipt, split, and settle in under a minute.",
    longDescription:
      "Full-stack SvelteKit + Cloudflare Workers with OpenRouter OCR pipeline and Durable Object realtime collaboration. Beta-tested by 50+ users.",
    highlights: [
      "4x faster OCR via stateful backend + cron resumption",
      "Realtime Durable Object: simultaneous item claiming, live split updates",
      "Expo mobile + SvelteKit web sharing D1/R2, Better-Auth, Drizzle",
    ],
    category: "fullstack",
    featured: true,
    status: "beta",
    tech: [
      "sveltekit",
      "svelte 5",
      "cloudflare workers",
      "durable objects",
      "d1",
      "r2",
      "expo",
      "react native",
      "drizzle",
      "better-auth",
      "pnpm workspaces",
    ],
    path: "fullStack/fair-share",
    links: { demo: "https://fairshares.app", github: "https://github.com/samuelj1323" },
    year: "2025",
  },
  {
    id: "warble",
    slug: "warble",
    title: "Warble",
    description:
      "Personalized speech-to-text — fine-tune Whisper on your own voice, run fully offline on Mac.",
    longDescription:
      "Python training pipeline (Colab) + native macOS SwiftUI app via WhisperKit/CoreML. Agent router classifies utterances for dictation vs Mac-control vs code-change (Claude Code harness).",
    highlights: [
      "Fine-tune openai/whisper-small on 1–2 hrs of personal audio",
      "WER eval stock vs fine-tuned, feedback loop via data/feedback",
      "On-device WhisperKit + CoreML, hotkey ⌘⇧D, paste into focused app",
    ],
    category: "ai",
    featured: true,
    status: "beta",
    tech: [
      "python",
      "pytorch",
      "transformers",
      "whisper",
      "whisperkit",
      "coreml",
      "swift",
      "swiftui",
      "fastapi",
      "uv",
    ],
    path: "ai/warble",
    links: { github: "https://github.com/samuelj1323/warble" },
    year: "2025",
  },
  {
    id: "structure-mfe",
    slug: "microfrontend-structure",
    title: "Microfrontend Structure",
    description:
      "Production MFE architecture example — Rollup-built React libs + host app.",
    longDescription:
      "Proves JPMorgan MFE/Market Risk bullet: shared tool-registration pattern, Module Federation analogue via Rollup.",
    highlights: [
      "Rollup + commonjs + terser building shared react 19 libs",
      "Host-app consuming federated modules",
      "Adopted pattern across 10+ apps org-wide",
    ],
    category: "frontend",
    featured: true,
    status: "live",
    tech: ["react 19", "rollup", "module federation", "typescript", "vite"],
    path: "frontend/packages/structure",
    links: {},
    year: "2024",
  },

  // ── Full-Stack ──
  {
    id: "instaweb",
    slug: "instaweb",
    title: "Instaweb (CMSaaS Starter)",
    description: "SvelteKit CMS starter with Supabase, S3, Stripe, and Vercel AI SDK.",
    highlights: [
      "Supabase auth + SSR, S3/Cloudinary media, Stripe billing",
      "Vercel AI SDK + instructor, MDX content, sveltekit-sse",
    ],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: [
      "sveltekit",
      "svelte 5",
      "supabase",
      "aws s3",
      "cloudinary",
      "stripe",
      "vercel ai sdk",
      "tailwind 4",
      "vitest",
    ],
    path: "fullStack/instaweb",
    links: {},
    year: "2025",
  },
  {
    id: "grocery-getter",
    slug: "grocery-getter",
    title: "Grocery Getter",
    description: "TanStack Start grocery planner with Postgres + Drizzle.",
    highlights: ["TanStack Start/Router SSR + Nitro", "Drizzle 0.45 + pg", "Vitest + jsdom + Testing Library"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["tanstack start", "tanstack router", "nitro", "drizzle", "postgres", "better-auth", "vitest"],
    path: "fullStack/grocery-getter",
    links: {},
    year: "2025",
  },
  {
    id: "pantry",
    slug: "pantry",
    title: "Pantry",
    description: "TanStack Start pantry inventory with Prisma.",
    highlights: ["Prisma 6.5 + Postgres", "TanStack Router 1.131 + Start"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["tanstack start", "tanstack router", "prisma", "postgres"],
    path: "fullStack/pantry",
    links: {},
    year: "2025",
  },
  {
    id: "budge",
    slug: "budge",
    title: "Budge",
    description: "Budgeting app — TanStack Start + Vercel Blob/KV.",
    highlights: ["Vercel Blob + KV", "TanStack Start nightly"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["tanstack start", "tanstack router", "vercel blob", "vercel kv"],
    path: "fullStack/budge",
    links: {},
    year: "2025",
  },
  {
    id: "going-dutch",
    slug: "going-dutch",
    title: "Going Dutch",
    description: "T3-stack bill splitter — Next.js + tRPC + Prisma.",
    highlights: ["tRPC 11 + TanStack Query", "NextAuth 5", "Prisma 6.5"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["next.js 15", "trpc", "prisma", "next-auth", "tailwind"],
    path: "fullStack/going_dutch",
    links: {},
    year: "2025",
  },
  {
    id: "wed-wise",
    slug: "wed-wise",
    title: "Wed Wise",
    description: "Wedding planner — T3 stack variant of Going Dutch.",
    highlights: ["T3 env + tRPC", "Prisma + Next.js App Router"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["next.js 15", "trpc", "prisma", "next-auth"],
    path: "fullStack/wed-wise",
    links: {},
    year: "2025",
  },
  {
    id: "heft",
    slug: "heft",
    title: "Heft",
    description: "Monorepo — Hono API on Cloudflare Workers + Expo mobile.",
    highlights: ["Hono + Workers + D1", "Expo + TanStack Query", "pnpm workspace:*"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["hono", "cloudflare workers", "d1", "expo", "react native", "tanstack query", "better-auth"],
    path: "fullStack/heft",
    links: {},
    year: "2025",
  },
  {
    id: "decodedpapers",
    slug: "decodedpapers",
    title: "DecodedPapers",
    description: "Astro research hub + Remotion video creation monorepo.",
    highlights: ["Astro 7 + MDX + RSS + Sharp", "Remotion 4 video pipeline", "pnpm 9.12 catalog"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["astro 7", "mdx", "remotion", "sharp", "pnpm"],
    path: "fullStack/decodedPapers",
    links: {},
    year: "2025",
  },
  {
    id: "ccost-v1",
    slug: "ccost-v1",
    title: "CCOST v1",
    description: "SvelteKit data viz with LayerChart + D3.",
    highlights: ["LayerChart 2 + d3-scale", "SvelteKit 2"],
    category: "frontend",
    featured: false,
    status: "wip",
    tech: ["sveltekit", "svelte 5", "layerchart", "d3", "tailwind"],
    path: "fullStack/ccost-v1",
    links: {},
    year: "2025",
  },
  {
    id: "pop",
    slug: "pop",
    title: "POP",
    description: "Vibe-designing platform — named components, iframe preview, AI assistant.",
    highlights: ["Svelte 5.55", "Vite iframe preview"],
    category: "frontend",
    featured: false,
    status: "wip",
    tech: ["svelte 5", "vite", "ai"],
    path: "fullStack/POP",
    links: {},
    year: "2025",
  },
  {
    id: "code-n-chaos",
    slug: "code-n-chaos",
    title: "CodeNChaos",
    description: "TanStack Start + Nitro experiment.",
    highlights: ["Nitro 3 + TanStack Router 1.168"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["tanstack start", "tanstack router", "nitro"],
    path: "fullStack/CodeNChaos",
    links: {},
    year: "2025",
  },
  {
    id: "delve-bound",
    slug: "delve-bound",
    title: "Delve Bound",
    description: "Cloudflare D1 game binder — Hono + Zustand + Tailwind.",
    highlights: ["D1 + Assets binding", "Zustand 5 + Hono 4.7", "wrangler deploy"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["hono", "d1", "wrangler", "zustand", "tailwind 4"],
    path: "fullStack/delve-bound",
    links: {},
    year: "2025",
  },
  {
    id: "tanstack-blog",
    slug: "tanstack-start-blog",
    title: "TanStack Start Blog",
    description: "Headless blog — TanStack Start + DB + Form + Table.",
    highlights: ["@tanstack/db 0.1 + react-form 1.0 + react-table 8.21", "Zod 4"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["tanstack start", "tanstack router", "tanstack db", "zod"],
    path: "fullStack/tanstack-start-blog",
    links: {},
    year: "2025",
  },
  {
    id: "ocuno",
    slug: "ocuno",
    title: "Ocuno",
    description: "Cursor-like OpenCode GUI — SolidJS + Electron.",
    highlights: ["SolidJS 1.9 + vite-plugin-solid", "Electron 42 + electron-vite + builder"],
    category: "harness",
    featured: false,
    status: "wip",
    tech: ["solidjs", "electron", "electron-vite", "vite"],
    path: "fullStack/ocuno",
    links: {},
    year: "2025",
  },
  {
    id: "schedule-goose",
    slug: "schedule-goose",
    title: "ScheduleGoose",
    description: "Scheduling app — Express 5 + TypeORM + Radix + tRPC.",
    highlights: ["TypeORM 0.3 + better-sqlite3", "6 Radix primitives", "tRPC TanStack"],
    category: "fullstack",
    featured: false,
    status: "wip",
    tech: ["express 5", "typeorm", "sqlite", "radix ui", "trpc", "react"],
    path: "fullStack/scheduleGoose",
    links: {},
    year: "2025",
  },
  {
    id: "nextjs-dashboard",
    slug: "nextjs-dashboard",
    title: "Next.js Dashboard",
    description: "Next.js 15 dashboard — Vercel Postgres + NextAuth + Turbopack.",
    highlights: ["App Router + Turbopack", "NextAuth 5 beta + postgres"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["next.js 15", "vercel postgres", "next-auth", "tailwind"],
    path: "fullStack/nextjs-dashboard",
    links: {},
    year: "2024",
  },

  // ── Harness / AI ──
  {
    id: "hardware-controller",
    slug: "hardware-controller",
    title: "Hardware Controller",
    description: "Native macOS app for VEC Infinity 3 foot controller with Local AI dictation.",
    longDescription: "Swift 6 harness — low-latency HID, audio boundary, on-device Ollama/Apple refinement, profile store.",
    highlights: [
      "Swift 6 + SwiftUI, HID manager, audio exception boundary",
      "Local AI dictation (on-device + Ollama loopback), no cloud",
      "Deterministic demo mode, signed hardware build",
    ],
    category: "harness",
    featured: false,
    status: "beta",
    tech: ["swift 6", "swiftui", "hid", "ollama", "coreml", "harness"],
    path: "harness/hardware_controller",
    links: { github: "https://github.com/MarcusJRLee/hardware_controller" },
    year: "2025",
  },
  {
    id: "t3-code-editor",
    slug: "t3-code-editor",
    title: "T3 Code Editor",
    description: "Web GUI for coding agents — wraps Codex/Claude via WebSocket JSON-RPC.",
    highlights: [
      "Node WS server + React/Vite UI, Effect/Schema contracts",
      "Performance/reliability-first, session restart resilience",
    ],
    category: "harness",
    featured: false,
    status: "wip",
    tech: ["react", "vite", "node", "websocket", "effect", "codex", "claude code"],
    path: "harness/t3-code-editor",
    links: {},
    year: "2025",
  },

  // ── Frontend ──
  {
    id: "svelte-portfolio",
    slug: "svelte-portfolio",
    title: "Svelte Portfolio",
    description: "Personal portfolio — SvelteKit + Tailwind 4 + Drizzle/better-sqlite3.",
    highlights: ["Svelte 5 + SvelteKit 2.22", "Tailwind 4 + forms", "Drizzle 0.40"],
    category: "frontend",
    featured: false,
    status: "live",
    tech: ["svelte 5", "sveltekit", "tailwind 4", "drizzle", "better-sqlite3"],
    path: "frontend/svelte/svelte-portfolio",
    links: {},
    year: "2025",
  },
  {
    id: "wing-suit",
    slug: "wing-suit",
    title: "Wing Suit",
    description: "Svelte + Three.js wingsuit viz via Threlte.",
    highlights: ["Three 0.180 + Threlte 8/9", "SvelteKit"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["svelte 5", "three.js", "threlte", "vite"],
    path: "frontend/svelte/wing-suit",
    links: {},
    year: "2025",
  },
  {
    id: "portfolio-react",
    slug: "portfolio",
    title: "Portfolio (this site)",
    description: "React 19 + Vite 8 + React Compiler + Biome/Oxlint.",
    highlights: ["React 19.2 + React Router 8", "Rolldown + React Compiler"],
    category: "frontend",
    featured: false,
    status: "live",
    tech: ["react 19", "vite 8", "react router", "biome", "oxlint", "typescript 6"],
    path: "frontend/react/portfolio",
    links: {},
    year: "2026",
  },
  {
    id: "white-board",
    slug: "white-board",
    title: "White Board",
    description: "Collaborative whiteboard — React + Electron + RoughJS canvas.",
    highlights: ["Electron 28", "RoughJS 4.6 canvas"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["react", "electron", "roughjs", "vite"],
    path: "frontend/react/white-board",
    links: {},
    year: "2024",
  },
  {
    id: "chat-app",
    slug: "chat-app",
    title: "Chat App",
    description: "Realtime chat — Express + Socket.io.",
    highlights: ["Socket.io 4.5 realtime", "Express 4.18"],
    category: "fullstack",
    featured: false,
    status: "demo",
    tech: ["react", "socket.io", "express", "node"],
    path: "frontend/react/chat-app",
    links: {},
    year: "2024",
  },
  {
    id: "trader-joes-planner",
    slug: "trader-joes-planner",
    title: "Trader Joe's Planner",
    description: "Meal planner — MUI + Redux Toolkit.",
    highlights: ["MUI 6.4 + Redux Toolkit 2.6", "React-Redux 9.2"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["react", "mui", "redux toolkit", "react-redux"],
    path: "frontend/react/trader-joes-planner",
    links: {},
    year: "2024",
  },
  {
    id: "wordle",
    slug: "wordle",
    title: "Wordle",
    description: "Wordle clone — MUI + Emotion.",
    highlights: ["MUI 5.15 + Emotion", "React 19"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["react", "mui", "emotion"],
    path: "frontend/react/wordle",
    links: {},
    year: "2024",
  },
  {
    id: "grocery-meal-planner",
    slug: "grocery-meal-planner",
    title: "Grocery Meal Planner",
    description: "Meal planner — Tailwind 4 + Radix + CVA.",
    highlights: ["Tailwind 4 + CVA + clsx + tailwind-merge", "Radix dialog/scroll-area/checkbox"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["react", "tailwind 4", "radix ui", "cva"],
    path: "frontend/react/grocery-meal-planner",
    links: {},
    year: "2025",
  },
  {
    id: "css-training",
    slug: "css-training",
    title: "CSS Training",
    description: "Interactive CSS trainer — CodeMirror + Framer Motion + Recharts.",
    highlights: ["CodeMirror 6 CSS/HTML/JS + One Dark", "Recharts 3.8"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["react", "codemirror", "framer motion", "recharts", "vite"],
    path: "frontend/react/CSS-Training",
    links: {},
    year: "2025",
  },
  {
    id: "spotify-clone",
    slug: "spotify-clone",
    title: "Spotify Clone",
    description: "Vue 3 + Pinia + Vue Router music app.",
    highlights: ["Vue 3.4 + Pinia persistedstate", "Vue Router 4.3"],
    category: "frontend",
    featured: false,
    status: "demo",
    tech: ["vue 3", "pinia", "vue router", "vite"],
    path: "frontend/vue/spotify-clone",
    links: {},
    year: "2024",
  },
  {
    id: "apples-to-apples",
    slug: "apples-to-apples",
    title: "Apples to Apples",
    description: "Vue card game — Bootstrap UI.",
    highlights: ["Vue 3.4 + Bootstrap 5.3"],
    category: "games",
    featured: false,
    status: "demo",
    tech: ["vue 3", "bootstrap", "vite"],
    path: "frontend/vue/apples-to-apples",
    links: {},
    year: "2024",
  },
  {
    id: "svelte-wing-suit",
    slug: "svelte-wing-suit-dup",
    title: "Svelte Wing Suit (dup)",
    description: "Duplicate entry merged — see wing-suit above.",
    highlights: [],
    category: "frontend",
    featured: false,
    status: "archived",
    tech: ["svelte"],
    path: "frontend/svelte/wing-suit",
    links: {},
    year: "2025",
  },

  // ── Backend / Infra ──
  {
    id: "postgres-drizzle",
    slug: "postgres-drizzle",
    title: "Postgres + Drizzle Learning",
    description: "Interactive Postgres + Drizzle ORM platform — Hono + Node.",
    highlights: ["Drizzle Kit generate/migrate", "Hono + @hono/node-server", "TSX watch"],
    category: "backend",
    featured: false,
    status: "learning",
    tech: ["hono", "drizzle", "postgres", "tsx", "node"],
    path: "backend/postgres-drizzle",
    links: {},
    year: "2025",
  },
  {
    id: "backend-learning",
    slug: "backend-learning",
    title: "Backend Learning",
    description: "Todo API — Node 22, Express, bcrypt/JWT, experimental SQLite.",
    highlights: ["Drizzle + pg", "JWT + bcrypt"],
    category: "backend",
    featured: false,
    status: "learning",
    tech: ["node", "express", "postgres", "drizzle", "jwt", "bcrypt"],
    path: "backend/backend-learning",
    links: {},
    year: "2024",
  },
  {
    id: "bird-brain",
    slug: "bird-brain",
    title: "Bird Brain",
    description: "Deno + Hono API experiment.",
    highlights: ["Deno 2 + jsr:@hono/hono 4.8"],
    category: "backend",
    featured: false,
    status: "demo",
    tech: ["deno", "hono", "typescript"],
    path: "backend/bird-brain",
    links: {},
    year: "2025",
  },
  {
    id: "pokemon-cacher",
    slug: "pokemon-cacher",
    title: "Pokemon Cacher",
    description: "PokeAPI cache — ioredis + Redis + Jest.",
    highlights: ["ioredis 5.3 + redis 7.2 docker-compose", "Jest + ts-jest + supertest"],
    category: "infra",
    featured: false,
    status: "demo",
    tech: ["ioredis", "redis", "docker compose", "jest", "typescript"],
    path: "dockerStart/pokemon-cacher",
    links: {},
    year: "2024",
  },
  {
    id: "backpack-debuggers",
    slug: "backpack-debuggers",
    title: "Backpack Debuggers",
    description: "Game monster API — Drizzle + PG.",
    highlights: ["Drizzle 0.30 + pg 8.11", "TSC alias"],
    category: "backend",
    featured: false,
    status: "demo",
    tech: ["drizzle", "postgres", "express", "typescript"],
    path: "dockerStart/backpack-debuggers",
    links: {},
    year: "2024",
  },

  // ── Games / ML (kept for completeness, filtered via extendedSkills in UI) ──
  {
    id: "beavers",
    slug: "hundreds-of-beavers",
    title: "Hundreds of Beavers",
    description: "Godot 4.4 game — 15 GDScript files (player, beaver, game).",
    highlights: ["Godot 4.4 + GDScript", "Film shader"],
    category: "games",
    featured: false,
    status: "wip",
    tech: ["godot 4.4", "gdscript", "glsl"],
    path: "games/beavers",
    links: {},
    year: "2025",
  },
  {
    id: "ox-games",
    slug: "ox-games",
    title: "Ox Games",
    description: "Godot arena/boss/singularity prototype.",
    highlights: ["Godot 4.4"],
    category: "games",
    featured: false,
    status: "wip",
    tech: ["godot 4.4", "gdscript"],
    path: "games/ox-games",
    links: {},
    year: "2025",
  },
  {
    id: "diffusion-writing",
    slug: "diffusion-writing",
    title: "Diffusion Handwriting",
    description: "PyTorch transformer handwriting diffusion — IAM dataset, FID/LPIPS.",
    highlights: ["Torch 2 + diffusion + wandb + tensorboard", "Custom positional encoding transformer"],
    category: "ai",
    featured: false,
    status: "archived",
    tech: ["pytorch", "python", "diffusers", "wandb", "tensorboard"],
    path: "ML/diffusion_writing",
    links: {},
    year: "2024",
  },
] as const satisfies Projects;

// Helpers for mapping — filter in UI without extra logic
export const featuredProjects = projects.filter((p) => p.featured);
export const projectsByCategory = (cat: (typeof projects)[number]["category"]) =>
  projects.filter((p) => p.category === cat);
export const projectsByTech = (tech: string) =>
  projects.filter((p) => p.tech.some((t) => t.toLowerCase().includes(tech.toLowerCase())));
